apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: daynightprint-micro
build: 
  local:
    push: false
    useDockerCLI: true
  artifacts:
    - image: daynightprint/backend 
      context: ./backend 
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: . 
    - image: daynightprint/client 
      context: ./client
      docker:
        dockerfile:  Dockerfile  
      sync:
        manual:
          - src: 'app/**/*' 
            dest: .
          - src: 'src/**/*'
            dest: .   
    - image: daynightprint/price-engine 
      context: ./price-engine
      docker:
        dockerfile:  Dockerfile  
      sync:
        manual:
          - src: 'app/**/*' 
            dest: . 

manifests:
  rawYaml:
    - infra/k8s/*
