apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: daynightprint/client
        imagePullPolicy: Never
        env:
          - name: NEXT_PUBLIC_API_URL
            value:  /api/v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec: 
  selector:
    app: client
  ports:
  - port: 3000
    targetPort: 3000

 