apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats.conf: |
    listen: 0.0.0.0:4222
    http: 0.0.0.0:8222

    jetstream {
      store_dir: "/data/jetstream"
      max_mem_store: 1Gb
      max_file_store: 10Gb
    }
 
